Repository thoth-station/graph-sync-scheduler, pull requests merged in 2019-09, with the labels that each got.

#61 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#62 Propagate deployment name for sentry environment
  openshift/deployment-template.yaml
Labels: approved, size/XS

#63 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#64 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot
