Repository thoth-station/graph-sync-scheduler, pull requests merged in 2019-08, with the labels that each got.

#54 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#55 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#56 Automatic update of dependency kubernetes from 9.0.0 to 9.0.1
  Pipfile.lock
Labels: bot

#58 Automatic update of dependency thoth-common from 0.9.6 to 0.9.8
  Pipfile.lock
Labels: bot

#59 Automatic update of dependency openshift from 0.9.0 to 0.8.0
  Pipfile.lock
Labels: bot

#60 Added config
  .thoth.yaml
Labels: approved, size/S
