Repository thoth-station/graph-sync-scheduler, pull requests merged in 2019-04, with the labels that each got.

#31 Automatic update of dependency thoth-common from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#32 Automatic update of dependency thoth-common from 0.8.2 to 0.8.3
  Pipfile.lock
Labels: bot

#33 Print version information on startup
  app.py
Labels: approved, size/XS

#34 Automatic update of dependency thoth-common from 0.8.3 to 0.8.4
  Pipfile.lock
Labels: bot

#35 Automatic update of dependency thoth-common from 0.8.4 to 0.8.5
  Pipfile.lock
Labels: bot

#36 Trigger graph-sync of dependency-monkey reports into graph database
  app.py
Labels: size/XS

#37 Automatic update of dependency openshift from 0.8.7 to 0.8.8
  Pipfile.lock
Labels: bot
