Repository thoth-station/graph-sync-scheduler, pull requests merged in 2019-03, with the labels that each got.

#25 reworks service account
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved

#28 Automatic update of dependency pyyaml from 3.13 to 5.1
  Pipfile.lock
Labels: bot

#29 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#27 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#30 Automatic update of dependency openshift from 0.8.6 to 0.8.7
  Pipfile.lock
Labels: bot
