Repository thoth-station/graph-sync-scheduler, pull requests merged in 2019-12, with the labels that each got.

#84 Automatic update of dependency pyyaml from 5.1.2 to 5.2
  Pipfile.lock
Labels: bot, size/S

#85 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/XS

#86 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/XS

#87 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#88 Automatic update of dependency openshift from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S

#89 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/XS
