Repository thoth-station/graph-sync-scheduler, pull requests merged in 2019-10, with the labels that each got.

#65 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#67 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#66 Simplify graph sync logic
  app.py
Labels: approved, size/M, size/XL

#70 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#74 Fix typo in attribute access
  app.py
Labels: approved, size/XS

#75 Fixing the leftover underscore
  app.py
Labels: approved, size/S

#76 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/S
